services:
  db:
    image: postgres:15-alpine
    container_name: erp_postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mobilya_erp"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - erp_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: erp_pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - erp_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: erp_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - erp_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: erp_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000/api/v1"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - erp_network

  storefront:
    build:
      context: ./storefront
      dockerfile: Dockerfile
    container_name: erp_storefront
    restart: always
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000/api/v1"
      GROQ_API_KEY: "${GROQ_API_KEY}"
    volumes:
      - ./storefront:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - erp_network

volumes:
  db_data:

networks:
  erp_network:
    driver: bridge