"""
Purchase Order model — tracks procurement of raw materials from suppliers.

Can be created manually or auto-generated by the MRP engine when
raw material stock is insufficient during production.
"""

import enum
from datetime import datetime

from sqlalchemy import String, Numeric, DateTime, Enum, ForeignKey, Integer, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class PurchaseOrderStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    ORDERED = "ORDERED"
    IN_TRANSIT = "IN_TRANSIT"
    RECEIVED = "RECEIVED"
    CANCELLED = "CANCELLED"


class PurchaseOrder(Base):
    __tablename__ = "purchase_orders"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    po_number: Mapped[str] = mapped_column(
        String(30), unique=True, nullable=False, index=True
    )
    supplier_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("suppliers.id"), nullable=False
    )
    item_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("items.id"), nullable=False
    )
    quantity: Mapped[float] = mapped_column(Numeric(12, 4), nullable=False)
    unit_cost: Mapped[float] = mapped_column(Numeric(12, 2), nullable=False)
    total_cost: Mapped[float] = mapped_column(Numeric(14, 2), nullable=False)
    status: Mapped[PurchaseOrderStatus] = mapped_column(
        Enum(PurchaseOrderStatus), default=PurchaseOrderStatus.DRAFT
    )
    order_date: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    expected_date: Mapped[datetime] = mapped_column(DateTime, nullable=True)
    received_date: Mapped[datetime] = mapped_column(DateTime, nullable=True)
    notes: Mapped[str] = mapped_column(Text, nullable=True)
    ordered_at: Mapped[datetime] = mapped_column(DateTime, nullable=True)
    estimated_delivery_at: Mapped[datetime] = mapped_column(DateTime, nullable=True)

    # FK to the production order that triggered this purchase (if auto-generated)
    triggered_by_production_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("production_orders.id"), nullable=True
    )

    # --- Relationships ---
    supplier = relationship("Supplier", back_populates="purchase_orders")
    item = relationship("Item")
    triggered_by_production = relationship("ProductionOrder")
    invoice = relationship("Invoice", back_populates="purchase_order", uselist=False)

    def __repr__(self) -> str:
        return f"<PurchaseOrder(po={self.po_number!r}, status={self.status.value})>"
