"""
Purchase Orders API — view procurement history (auto-generated by MRP + manual).
"""

import asyncio
from datetime import datetime, timedelta, timezone
from pydantic import BaseModel
from fastapi import APIRouter, Depends, HTTPException, BackgroundTasks
from sqlalchemy.orm import Session, joinedload

from app.core.deps import get_db, RequireRole
from app.db.session import SessionLocal
from app.models.user import UserRole
from app.models.item import Item, ItemType
from app.models.purchase_order import PurchaseOrder, PurchaseOrderStatus
from app.services.stock_evaluator import evaluate_stock_levels

router = APIRouter(prefix="/purchase-orders", tags=["Purchase Orders"])


def _utc_iso(dt):
    """Convert a naive-UTC datetime to an ISO string with 'Z' suffix for correct JS parsing."""
    if dt is None:
        return None
    return dt.isoformat() + "Z"


class PurchaseOrderCreate(BaseModel):
    supplier_id: int
    item_id: int
    quantity: float


# simulate_delivery has been moved to DB-backed ScheduledTask for crash resilience

@router.get("/")
def list_purchase_orders(
    status: str = None,
    db: Session = Depends(get_db),
):
    query = db.query(PurchaseOrder).options(
        joinedload(PurchaseOrder.supplier),
        joinedload(PurchaseOrder.item),
    )
    if status:
        query = query.filter(PurchaseOrder.status == PurchaseOrderStatus(status))

    pos = query.order_by(PurchaseOrder.order_date.desc()).all()

    return [
        {
            "id": po.id,
            "po_number": po.po_number,
            "supplier_name": po.supplier.name,
            "supplier_id": po.supplier_id,
            "item_name": po.item.name,
            "item_sku": po.item.sku,
            "item_id": po.item_id,
            "quantity": float(po.quantity),
            "unit_cost": float(po.unit_cost),
            "total_cost": float(po.total_cost),
            "status": po.status.value,
            "order_date": _utc_iso(po.order_date),
            "ordered_at": _utc_iso(po.ordered_at),
            "estimated_delivery_at": _utc_iso(po.estimated_delivery_at),
            "received_date": _utc_iso(po.received_date),
            "notes": po.notes,
            "triggered_by_production_id": po.triggered_by_production_id,
        }
        for po in pos
    ]


@router.post("/")
def create_purchase_order(
    data: PurchaseOrderCreate, 
    db: Session = Depends(get_db),
    _=Depends(RequireRole([UserRole.FACTORY_MANAGER, UserRole.ADMIN]))
):
    """Manually create a DRAFT purchase order (Raw Materials only)."""
    item = db.get(Item, data.item_id)
    if not item:
        raise HTTPException(404, "Item not found")
    if item.item_type != ItemType.RAW_MATERIAL:
        raise HTTPException(400, "Purchase orders can only be created for RAW_MATERIAL items.")
    
    # Generate PO Number
    po_count = db.query(PurchaseOrder).count()
    po_number = f"PO-{datetime.utcnow().strftime('%Y%m')}-{po_count + 1:04d}"

    po = PurchaseOrder(
        po_number=po_number,
        supplier_id=data.supplier_id,
        item_id=data.item_id,
        quantity=data.quantity,
        unit_cost=item.unit_cost,
        total_cost=float(item.unit_cost) * data.quantity,
        status=PurchaseOrderStatus.DRAFT,
        notes="Manually created"
    )
    db.add(po)
    db.commit()
    db.refresh(po)
    
    return {
        "id": po.id,
        "po_number": po.po_number,
        "status": po.status.value
    }


@router.patch("/{po_id}/approve")
def approve_purchase_order(
    po_id: int, 
    db: Session = Depends(get_db),
    _=Depends(RequireRole([UserRole.FACTORY_MANAGER, UserRole.ADMIN]))
):
    """Approve a DRAFT purchase order, moving it to ORDERED."""
    po = db.get(PurchaseOrder, po_id)
    if not po:
        raise HTTPException(404, "Purchase order not found")
    if po.status != PurchaseOrderStatus.DRAFT:
        raise HTTPException(400, f"Cannot approve PO in status: {po.status.value}")
    
    po.status = PurchaseOrderStatus.ORDERED
    db.commit()
    return {"id": po.id, "status": po.status.value}


@router.post("/{po_id}/order")
def order_purchase_order(
    po_id: int,
    background_tasks: BackgroundTasks,
    db: Session = Depends(get_db),
    _=Depends(RequireRole([UserRole.FACTORY_MANAGER, UserRole.ADMIN]))
):
    """Approve/Order a DRAFT PO: set ORDERED, timestamps, and start delivery simulation (5s→IN_TRANSIT→15s→RECEIVED)."""
    po = db.get(PurchaseOrder, po_id)
    if not po:
        raise HTTPException(404, "Purchase order not found")
    if po.status != PurchaseOrderStatus.DRAFT:
        raise HTTPException(400, f"Cannot order PO in status: {po.status.value}")

    po.status = PurchaseOrderStatus.ORDERED
    po.ordered_at = datetime.utcnow()
    po.estimated_delivery_at = datetime.utcnow() + timedelta(seconds=20)  # 5s + 15s total
    db.commit()

    # Start delivery simulation using DB backed task queue
    from app.models.scheduled_task import ScheduledTask, TaskType
    task = ScheduledTask(
        task_type=TaskType.DELIVERY_TRANSIT,
        target_id=po.id,
        execute_at=datetime.utcnow() + timedelta(seconds=5)
    )
    db.add(task)
    db.commit()

    return {
        "id": po.id,
        "po_number": po.po_number,
        "status": po.status.value,
        "ordered_at": _utc_iso(po.ordered_at),
        "estimated_delivery_at": _utc_iso(po.estimated_delivery_at),
    }


@router.get("/{po_id}")
def get_purchase_order(po_id: int, db: Session = Depends(get_db)):
    po = (
        db.query(PurchaseOrder)
        .options(joinedload(PurchaseOrder.supplier), joinedload(PurchaseOrder.item))
        .get(po_id)
    )
    if not po:
        raise HTTPException(404, detail="Purchase order not found")
    return {
        "id": po.id,
        "po_number": po.po_number,
        "supplier": {"id": po.supplier.id, "name": po.supplier.name},
        "item": {"id": po.item.id, "name": po.item.name, "sku": po.item.sku},
        "quantity": float(po.quantity),
        "unit_cost": float(po.unit_cost),
        "total_cost": float(po.total_cost),
        "status": po.status.value,
        "order_date": _utc_iso(po.order_date),
        "ordered_at": _utc_iso(po.ordered_at),
        "estimated_delivery_at": _utc_iso(po.estimated_delivery_at),
        "received_date": _utc_iso(po.received_date),
        "notes": po.notes,
    }


@router.patch("/{po_id}/receive")
def receive_purchase_order(po_id: int, db: Session = Depends(get_db)):
    """Mark a purchase order as received and add stock to the item."""
    po = db.get(PurchaseOrder, po_id)
    if not po:
        raise HTTPException(404, detail="Purchase order not found")
    if po.status == PurchaseOrderStatus.RECEIVED:
        raise HTTPException(400, detail="Already received")

    po.status = PurchaseOrderStatus.RECEIVED
    po.received_date = datetime.utcnow()

    # Add purchased quantity to item stock
    po.item.stock_quantity = float(po.item.stock_quantity) + float(po.quantity)

    from app.models.stock_lot import StockLot
    lot = StockLot(
        item_id=po.item.id,
        source_type="PURCHASE",
        source_id=po.id,
        initial_quantity=po.quantity,
        remaining_quantity=po.quantity,
        unit_cost=float(po.unit_cost),
    )
    db.add(lot)

    # Auto-generate PURCHASE invoice
    from app.services.finance_service import generate_purchase_invoice
    generate_purchase_invoice(db, po)

    # Record expense in ledger
    from app.services.ledger_service import record_expense
    record_expense(db, po)

    db.commit()
    
    evaluate_stock_levels(db, po.item.id)
    db.commit()

    return {
        "po_number": po.po_number,
        "status": po.status.value,
        "item_new_stock": float(po.item.stock_quantity),
    }
